name: selfhosted-qliksense-ci
on:
  push:
    branches:
      - main

jobs:
  # Copy script files from GitHub repository to Qlik Sense script folder
  selfhosted-qliksense-ci:
    runs-on: [self-hosted, windows, X64, qliksense-ci]
    steps:
    - uses: actions/checkout@v2

    - name: Debug 
      run: dir

    - name: Copy script files 
      run: .\powershell\copyfiles_demo1.ps1 `
            -paramUsername '${{ secrets.FILESHARE_USERNAME }}' `
            -paramPassword '${{ secrets.FILESHARE_PASSWORD }}' `
            -paramFileShareLetter '${{ secrets.FILESHARE_LETTER }}' `
            -paramFileShareUNC '${{ secrets.FILESHARE_UNC }}'
      # run: $username = "${{ secrets.FILESHARE_USERNAME }}"; $password = ConvertTo-SecureString "${{ secrets.FILESHARE_PASSWORD }}" -AsPlainText -Force; $cred = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $password); New-PSDrive -Name "${{ secrets.FILESHARE_LETTER }}" -Root "${{ secrets.FILESHARE_UNC }}" -PSProvider "FileSystem" -Credential $cred; Copy-Item "scripts" -Destination "${{ secrets.FILESHARE_LETTER }}:\ci_demo" -Recurse; Remove-PSDrive -Name ${{ secrets.FILESHARE_LETTER }}

    - name: Reload app "CI demo"
      uses: fjogeleit/http-request-action@master
      with:
        url: 'http://192.168.100.112:8080/v4/reloadtask/4174b1ec-0fd1-4cbe-8d47-0afe545d69bd/start'
        method: 'PUT'
        # username: 
        # password: 